export const currencyByRupee: Currency[] = [
    {
      name: 'DOLLAR',
      value: 0.012271428,
      flag: '🇺🇸',
      symbol: '$',
    },
    {
      name: 'EURO',
      value: 0.01125809,
      flag: '🇪🇺',
      symbol: '€',
    },
    {
      name: 'POUND',
      value: 0.0099194378,
      flag: '🇬🇧',
      symbol: '£',
    },
    {
      name: 'RUBEL',
      value: 0.85040469,
      flag: '🇷🇺',
      symbol: '₽',
    },
    {
      name: 'AUS DOLLAR',
      value: 0.01732574,
      flag: '🇦🇺',
      symbol: 'A$',
    },
    {
      name: 'CAN DOLLAR',
      value: 0.016457908,
      flag: '🇨🇦',
      symbol: 'C$',
    },
    {
      name: 'YEN',
      value: 1.5909089,
      flag: '🇯🇵',
      symbol: '¥',
    },
    {
      name: 'DINAR',
      value: 0.0037446993,
      flag: '🇰🇼',
      symbol: 'KD',
    },
    {
      name: 'BITCOIN',
      value: 0.000000543544886,
      flag: '🎰',
      symbol: '₿',
    },
    {
      name: 'SINGAPORE DOLLAR',
      value: 0.0165921,
      flag: '🇸🇬',
      symbol: 'S$',
    },
    {
      name: 'SWISS FRANC',
      value: 0.0103505,
      flag: '🇨🇭',
      symbol: 'CHF',
    },
    {
      name: 'CHINESE YUAN',
      value: 0.089635,
      flag: '🇨🇳',
      symbol: '¥',
    },
    {
      name: 'UAE DIRHAM',
      value: 0.045075,
      flag: '🇦🇪',
      symbol: 'AED',
    },
    {
      name: 'SOUTH AFRICAN RAND',
      value: 0.231045,
      flag: '🇿🇦',
      symbol: 'R',
    },
    {
      name: 'BRAZILIAN REAL',
      value: 0.0619245,
      flag: '🇧🇷',
      symbol: 'R$',
    },
    {
      name: 'MEXICAN PESO',
      value: 0.213208,
      flag: '🇲🇽',
      symbol: 'MX$',
    },
    {
      name: 'THAI BAHT',
      value: 0.44185,
      flag: '🇹🇭',
      symbol: '฿',
    },
    {
      name: 'INDONESIAN RUPIAH',
      value: 190.72352,
      flag: '🇮🇩',
      symbol: 'Rp',
    },
    {
      name: 'MALAYSIAN RINGGIT',
      value: 0.0560271,
      flag: '🇲🇾',
      symbol: 'RM',
    },
    {
      name: 'EGYPTIAN POUND',
      value: 0.378195,
      flag: '🇪🇬',
      symbol: 'E£',
    },
    {
      name: 'PHILIPPINE PESO',
      value: 0.688704,
      flag: '🇵🇭',
      symbol: '₱',
    },
    {
      name: 'VIETNAMESE DONG',
      value: 295.768,
      flag: '🇻🇳',
      symbol: '₫',
    },
    {
      name: 'NEW ZEALAND DOLLAR',
      value: 0.020168,
      flag: '🇳🇿',
      symbol: 'NZ$',
    },
    {
      name: 'HONG KONG DOLLAR',
      value: 0.095748,
      flag: '🇭🇰',
      symbol: 'HK$',
    },
    {
      name: 'TURKISH LIRA',
      value: 0.025314,
      flag: '🇹🇷',
      symbol: '₺',
    },
    {
      name: 'SAUDI RIYAL',
      value: 0.045069,
      flag: '🇸🇦',
      symbol: 'SAR',
    },
    {
      name: 'NORWEGIAN KRONE',
      value: 0.136731,
      flag: '🇳🇴',
      symbol: 'kr',
    },
    {
      name: 'SOUTH KOREAN WON',
      value: 16.2605,
      flag: '🇰🇷',
      symbol: '₩',
    },
    {
      name: 'ARGENTINIAN PESO',
      value: 4.09385,
      flag: '🇦🇷',
      symbol: 'ARS$',
    },
    {
      name: 'BANGLADESHI TAKA',
      value: 1.34,
      flag: '🇧🇩',
      symbol: '৳',
    },
    {
      name: 'NEPALESE RUPEE',
      value: 1.6,
      flag: '🇳🇵',
      symbol: 'रू',
    },
    {
      name: 'PAKISTANI RUPEE',
      value: 3.83,
      flag: '🇵🇰',
      symbol: '₨',
    },
    {
      name: 'SRI LANKAN RUPEE',
      value: 3.98,
      flag: '🇱🇰',
      symbol: 'Rs',
    },
    {
      name: 'QATARI RIYAL',
      value: 0.045,
      flag: '🇶🇦',
      symbol: 'QAR',
    },
    {
      name: 'CHILEAN PESO',
      value: 10.56,
      flag: '🇨🇱',
      symbol: 'CLP$',
    },
    {
      name: 'POLISH ZLOTY',
      value: 0.0512,
      flag: '🇵🇱',
      symbol: 'zł',
    },
    {
      name: 'SWEDISH KRONA',
      value: 0.1389,
      flag: '🇸🇪',
      symbol: 'kr',
    },
    {
      name: 'HUNGARIAN FORINT',
      value: 4.38,
      flag: '🇭🇺',
      symbol: 'Ft',
    },
    {
      name: 'ISRAELI SHEKEL',
      value: 0.0462,
      flag: '🇮🇱',
      symbol: '₪',
    },
    {
      name: 'JORDANIAN DINAR',
      value: 0.00877,
      flag: '🇯🇴',
      symbol: 'JD',
    },
    {
      name: 'CZECH KORUNA',
      value: 0.2758,
      flag: '🇨🇿',
      symbol: 'Kč',
    },
    {
      name: 'ICELANDIC KRONA',
      value: 1.668,
      flag: '🇮🇸',
      symbol: 'ISK',
    },
    {
      name: 'MYANMAR KYAT',
      value: 25.83,
      flag: '🇲🇲',
      symbol: 'K',
    },
    {
      name: 'OMANI RIYAL',
      value: 0.0047,
      flag: '🇴🇲',
      symbol: 'OMR',
    },
    {
      name: 'TANZANIAN SHILLING',
      value: 30.85,
      flag: '🇹🇿',
      symbol: 'TSh',
    },
  ];